/**
 * Blog featured image sourcing — searches multiple free image APIs to find
 * images that match the article content. Falls back to AI generation if
 * no stock photo matches.
 *
 * Sources (in order):
 *   1. Unsplash API (free, 50 req/hour) — real photos, high quality
 *   2. Pexels API (free, 200 req/hour) — real photos
 *   3. Pixabay API (free, 100 req/minute) — real photos + illustrations
 *   4. AI image generation (via /api/ai/generate-image) — if all else fails
 *
 * Get free API keys:
 *   - Unsplash: https://unsplash.com/developers → Access Key
 *   - Pexels: https://www.pexels.com/api/ → API Key
 *   - Pixabay: https://pixabay.com/api/docs/ → API Key
 */

export type SourcedImage = { url: string; alt: string; credit: string } | null;

/**
 * Search Unsplash for a photo matching the query.
 */
async function searchUnsplash(query: string): Promise<SourcedImage> {
  const key = process.env.UNSPLASH_ACCESS_KEY;
  if (!key || !query.trim()) return null;

  try {
    const res = await fetch(
      `https://api.unsplash.com/search/photos?query=${encodeURIComponent(query)}&per_page=3&orientation=landscape`,
      { headers: { Authorization: `Client-ID ${key}` }, signal: AbortSignal.timeout(15_000) },
    );
    if (!res.ok) return null;
    const data = await res.json();
    const photo = data?.results?.[0];
    if (!photo) return null;

    return {
      url: photo.urls.regular,
      alt: photo.alt_description || query,
      credit: photo.user?.name ? `Photo by ${photo.user.name} on Unsplash` : "Unsplash",
    };
  } catch {
    return null;
  }
}

/**
 * Search Pexels for a photo matching the query.
 */
async function searchPexels(query: string): Promise<SourcedImage> {
  const key = process.env.PEXELS_API_KEY;
  if (!key || !query.trim()) return null;

  try {
    const res = await fetch(
      `https://api.pexels.com/v1/search?query=${encodeURIComponent(query)}&per_page=3&orientation=landscape`,
      { headers: { Authorization: key }, signal: AbortSignal.timeout(15_000) },
    );
    if (!res.ok) return null;
    const data = await res.json();
    const photo = data?.photos?.[0];
    if (!photo) return null;

    return {
      url: photo.src?.large || photo.src?.medium || photo.src?.original,
      alt: photo.alt || query,
      credit: photo.photographer ? `Photo by ${photo.photographer} on Pexels` : "Pexels",
    };
  } catch {
    return null;
  }
}

/**
 * Search Pixabay for a photo matching the query.
 */
async function searchPixabay(query: string): Promise<SourcedImage> {
  const key = process.env.PIXABAY_API_KEY;
  if (!key || !query.trim()) return null;

  try {
    const res = await fetch(
      `https://pixabay.com/api/?key=${key}&q=${encodeURIComponent(query)}&image_type=photo&orientation=horizontal&per_page=3&safesearch=true`,
      { signal: AbortSignal.timeout(15_000) },
    );
    if (!res.ok) return null;
    const data = await res.json();
    const hit = data?.hits?.[0];
    if (!hit) return null;

    return {
      url: hit.largeImageURL || hit.webformatURL || hit.previewURL,
      alt: hit.tags || query,
      credit: hit.user ? `Photo by ${hit.user} on Pixabay` : "Pixabay",
    };
  } catch {
    return null;
  }
}

/**
 * Generate an image using the AI image generation endpoint.
 * Uses the Gemini Imagen's image generation (free, no API key needed).
 */
async function generateAIImage(query: string): Promise<SourcedImage> {
  if (!query.trim()) return null;

  try {
    // Call our own /api/ai/generate-image endpoint which uses the
    // Gemini Imagen to generate an image from a text prompt.
    const prompt = `Premium fitness blog image: ${query}. Ultra realistic, professional lighting, high quality, no text overlay.`;
    const res = await fetch(
      `${process.env.NEXT_PUBLIC_APP_URL || "https://musclehubeg.vercel.app"}/api/ai/generate-image?prompt=${encodeURIComponent(prompt)}`,
      { signal: AbortSignal.timeout(60_000) },
    );
    if (!res.ok) return null;
    const data = await res.json();
    if (!data?.url) return null;

    return {
      url: data.url,
      alt: query,
      credit: "AI-generated by MuscleHub",
    };
  } catch {
    return null;
  }
}

/**
 * Fetch a featured image for a blog article.
 * Tries multiple sources in order: Unsplash → Pexels → Pixabay → AI generation.
 * Returns the first successful result, or null if all fail.
 */
export async function fetchFeaturedImage(query: string): Promise<SourcedImage> {
  if (!query.trim()) return null;

  // Try each source in order — return the first that succeeds
  const sources = [
    () => searchUnsplash(query),
    () => searchPexels(query),
    () => searchPixabay(query),
    () => generateAIImage(query),
  ];

  for (const source of sources) {
    const result = await source();
    if (result) return result;
  }

  return null;
}

/**
 * Fetch a featured image using multiple search queries (tries each query
 * across all sources before giving up). Useful when the first query is too
 * specific — falls back to broader queries.
 */
export async function fetchFeaturedImageMultiQuery(queries: string[]): Promise<SourcedImage> {
  for (const query of queries) {
    const result = await fetchFeaturedImage(query);
    if (result) return result;
  }
  return null;
}
