"use client";

/**
 * AffiliateToolkit — authenticated section that shows:
 *   1. The user's personal Affiliate Link (with CopyButton)
 *   2. Ready-to-publish promotional content (5 templates, each copyable)
 *   3. Website banners with HTML embed codes (4 formats, each copyable)
 *
 * SECURITY:
 *   - All HTML embed code is generated by buildBannerEmbedHtml() — a
 *     trusted string template. The user NEVER enters HTML.
 *   - Dynamic values (affiliate URL, banner URL) are escaped via
 *     escapeHtml() before insertion.
 *   - The user's affiliate code only ever appears inside the affiliate URL
 *     (encoded) — never as raw HTML attributes or scripts.
 *   - All <a> tags in the generated embed use target="_blank"
 *     rel="noopener noreferrer".
 *
 * LAYOUT:
 *   - Mobile-first. Cards stack vertically on small screens.
 *   - Code blocks use overflow-x-auto so long URLs never overflow.
 *   - Buttons have min 44px tap target.
 *
 * LOCALIZATION:
 *   - 100% English when lang === "en", 100% Arabic when lang === "ar".
 *   - Brand name "Alkemos" is never translated.
 */

import { useEffect, useMemo, useState } from "react";
import { useAuth } from "@/hooks/use-auth";
import { useI18n } from "@/lib/i18n";
import {
  getOrCreateReferralCode,
} from "@/lib/referral";
import { CopyButton } from "@/components/ui/copy-button";
import {
  BANNER_FORMATS,
  PROMO_TEMPLATES,
  buildAffiliateUrl,
  buildBannerEmbedHtml,
  buildPromoCopy,
  getBannerUrl,
  type BannerFormat,
  type BannerLang,
  type PromoTemplate,
} from "@/lib/affiliate-content";
import { FileText, LayoutGrid, Image as ImageIcon, AlertCircle } from "lucide-react";

export function AffiliateToolkit() {
  const { t, lang } = useI18n();
  const { profile } = useAuth();
  const isAr = lang === "ar";
  const dir = isAr ? "rtl" : "ltr";

  const [referralCode, setReferralCode] = useState<string>("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // ─── Banner language selector state ───
  // Independent from the UI language — lets the affiliate owner choose
  // which language the actual banner CONTENT renders in (for their site
  // visitors). Defaults to the current UI language for convenience.
  const [bannerLang, setBannerLang] = useState<BannerLang>(isAr ? "ar" : "en");

  // ─── Load the user's real referral code ───
  useEffect(() => {
    let cancelled = false;
    (async () => {
      if (!profile?.id) return;
      try {
        const code = await getOrCreateReferralCode(profile.id, profile.full_name);
        if (!cancelled) {
          setReferralCode(code);
          setError(null);
        }
      } catch (e) {
        if (!cancelled) {
          setError(
            e instanceof Error
              ? e.message
              : (isAr
                ? "تعذر تحميل رابط الأفلييت"
                : "Couldn't load your affiliate link"),
          );
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [profile?.id, profile?.full_name, isAr]);

  // ─── Compute affiliate URL ───
  const affiliateUrl = useMemo(() => {
    if (!referralCode) return "";
    return buildAffiliateUrl(referralCode);
  }, [referralCode]);

  // ─── Localized UI strings ───
  const ui = useMemo(() => getUi(isAr), [isAr]);

  // ─── Loading state ───
  if (loading) {
    return (
      <div className="marble-card p-8 text-center text-base font-normal text-[var(--muted-foreground)]">
        {t("common.loading")}
      </div>
    );
  }

  // ─── Error state ───
  if (error || !referralCode || !affiliateUrl) {
    return (
      <div className="rounded-3xl border border-[#ff3b30]/20 bg-[#ff3b30]/5 p-8">
        <div className="flex items-start gap-3">
          <AlertCircle className="mt-0.5 h-5 w-5 shrink-0 text-[#ff3b30]" aria-hidden="true" />
          <div>
            <p className="text-base font-semibold text-[var(--text)]">
              {isAr ? "تعذر تحميل رابط الأفلييت" : "Couldn't load your affiliate link"}
            </p>
            <p className="mt-1 text-sm font-normal text-[var(--muted-foreground)]">
              {error || (isAr ? "حاول مرة تانية أو تواصل مع الدعم." : "Please try again or contact support.")}
            </p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div dir={dir} className="space-y-10">
      {/* ─── 1. READY-TO-PUBLISH CONTENT ─── */}
      <section
        id="affiliate-content"
        aria-labelledby="affiliate-content-h"
        className="marble-card p-6 sm:p-8 md:p-10"
      >
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-2xl border border-[var(--edge)] bg-[var(--tint)]">
            <FileText className="h-5 w-5 text-[var(--muted-2)]" aria-hidden="true" />
          </div>
          <h2 id="affiliate-content-h" className="text-xl font-semibold tracking-tight sm:text-2xl">
            {ui.content.title}
          </h2>
        </div>
        <p className="mt-3 text-sm font-normal text-[var(--muted-foreground)]">
          {ui.content.subtitle}
        </p>

        <div className="mt-8 grid gap-4 sm:grid-cols-2">
          {PROMO_TEMPLATES.map((tpl) => (
            <PromoCard
              key={tpl.id}
              template={tpl}
              affiliateUrl={affiliateUrl}
              isAr={isAr}
              ui={ui}
            />
          ))}
        </div>
      </section>

      {/* ─── 2. WEBSITE BANNERS ─── */}
      <section
        id="affiliate-banners"
        aria-labelledby="affiliate-banners-h"
        className="marble-card p-6 sm:p-8 md:p-10"
      >
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[#34c759]/15">
            <ImageIcon className="h-5 w-5 text-[#1d8a3d]" aria-hidden="true" />
          </div>
          <h2 id="affiliate-banners-h" className="text-xl font-semibold tracking-tight sm:text-2xl">
            {ui.banners.title}
          </h2>
        </div>
        <p className="mt-3 text-sm font-normal text-[var(--muted-foreground)]">
          {ui.banners.subtitle}
        </p>

        {/* Banner language selector — independent from UI language */}
        <BannerLangSelector
          bannerLang={bannerLang}
          onBannerLangChange={setBannerLang}
          isAr={isAr}
          labels={ui.banners.langSelector}
        />

        <div className="mt-8 grid gap-4 md:grid-cols-2">
          {BANNER_FORMATS.map((format) => (
            <BannerCard
              key={format.id}
              format={format}
              affiliateUrl={affiliateUrl}
              isAr={isAr}
              bannerLang={bannerLang}
              ui={ui}
            />
          ))}
        </div>
      </section>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────
// Sub-component: BannerLangSelector
// ─────────────────────────────────────────────────────────────────────────

/**
 * BannerLangSelector — segmented control that lets the affiliate owner
 * choose which language the banner CONTENT renders in.
 *
 * This is INDEPENDENT from the UI language — an Arabic-speaking affiliate
 * may want to display English banners on an English-speaking site, and
 * vice versa. The selected language flows into:
 *   - Which SVG asset (EN or AR) is rendered in the preview
 *   - Which SVG asset URL is embedded in the HTML code
 *   - The `alt` attribute on the embedded <img>
 */
function BannerLangSelector({
  bannerLang,
  onBannerLangChange,
  isAr,
  labels,
}: {
  bannerLang: BannerLang;
  onBannerLangChange: (lang: BannerLang) => void;
  isAr: boolean;
  labels: { title: string; en: string; ar: string; hint: string };
}) {
  return (
    <div
      className="marble-card mt-6 flex flex-col gap-2 p-4 sm:flex-row sm:items-center sm:justify-between sm:gap-4"
      role="group"
      aria-label={labels.title}
    >
      <div className="flex flex-col gap-1">
        <span className="text-sm font-semibold text-[var(--text)]">
          {labels.title}
        </span>
        <span className="text-xs font-normal text-[var(--muted-foreground)]">
          {labels.hint}
        </span>
      </div>

      {/* Segmented control — Apple-style pill toggle */}
      <div
        className="inline-flex w-full max-w-full shrink-0 overflow-hidden rounded-full border border-[var(--edge)] bg-[var(--tint)] p-1 sm:w-auto"
        role="radiogroup"
        aria-label={labels.title}
      >
        <button
          type="button"
          role="radio"
          aria-checked={bannerLang === "en"}
          onClick={() => onBannerLangChange("en")}
          className={
            "flex flex-1 items-center justify-center gap-2 rounded-full px-5 py-2 text-sm font-semibold transition-colors sm:flex-none " +
            (bannerLang === "en"
              ? "bg-[var(--text)] text-[var(--bg)] shadow-sm"
              : "text-[var(--muted-foreground)] hover:text-[var(--text)]")
          }
        >
          {labels.en}
        </button>
        <button
          type="button"
          role="radio"
          aria-checked={bannerLang === "ar"}
          onClick={() => onBannerLangChange("ar")}
          className={
            "flex flex-1 items-center justify-center gap-2 rounded-full px-5 py-2 text-sm font-semibold transition-colors sm:flex-none " +
            (bannerLang === "ar"
              ? "bg-[var(--text)] text-[var(--bg)] shadow-sm"
              : "text-[var(--muted-foreground)] hover:text-[var(--text)]")
          }
          dir="rtl"
        >
          {labels.ar}
        </button>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────
// Sub-component: PromoCard
// ─────────────────────────────────────────────────────────────────────────

function PromoCard({
  template,
  affiliateUrl,
  isAr,
  ui,
}: {
  template: PromoTemplate;
  affiliateUrl: string;
  isAr: boolean;
  ui: UiStrings;
}) {
  const copy = useMemo(
    () => buildPromoCopy(template, affiliateUrl, isAr),
    [template, affiliateUrl, isAr],
  );

  const label = isAr ? template.label_ar : template.label_en;
  const platform = isAr ? template.recommendedPlatform_ar : template.recommendedPlatform_en;

  return (
    <article className="marble-card flex min-w-0 flex-col p-5">
      <header>
        <h3 className="text-base font-semibold tracking-tight">{label}</h3>
        <p className="mt-1 text-xs font-normal text-[var(--muted-foreground)]">
          {isAr ? "منصة موصى بها" : "Recommended platform"}: {platform}
        </p>
      </header>

      {/* Copy preview — scrollable on mobile, no horizontal overflow */}
      <div
        className="mt-4 max-h-48 overflow-y-auto rounded-xl bg-[#fafafa] p-4"
        role="region"
        aria-label={isAr ? "معاينة النص" : "Copy preview"}
      >
        <pre
          dir={isAr ? "rtl" : "ltr"}
          className="whitespace-pre-wrap break-words font-sans text-sm font-normal leading-relaxed text-[var(--text)]"
        >
          {copy}
        </pre>
      </div>

      {/* Footer: char count + copy button */}
      <footer className="mt-4 flex items-center justify-between gap-3">
        <span className="text-xs font-normal text-[#8e8e93]">
          {copy.length} {isAr ? "حرف" : "chars"}
        </span>
        <CopyButton
          value={copy}
          label={isAr ? "نسخ" : "Copy"}
          successLabel={ui.common.copied}
          errorLabel={ui.common.copyError}
          variant="secondary"
          analyticsEvent="affiliate_template_copied"
          analyticsPayload={{ template: template.id }}
          ariaLabel={isAr ? `نسخ قالب ${label}` : `Copy ${label} template`}
        />
      </footer>
    </article>
  );
}

// ─────────────────────────────────────────────────────────────────────────
// Sub-component: BannerCard
// ─────────────────────────────────────────────────────────────────────────

function BannerCard({
  format,
  affiliateUrl,
  isAr,
  bannerLang,
  ui,
}: {
  format: BannerFormat;
  affiliateUrl: string;
  isAr: boolean;
  bannerLang: BannerLang;
  ui: UiStrings;
}) {
  // Generate the trusted HTML embed code (server-side template + escaped values).
  // The banner language is chosen by the affiliate owner via the
  // BannerLangSelector — this determines which SVG asset (EN or AR) is
  // embedded. The UI language (isAr) only affects chrome text/labels.
  const html = useMemo(
    () => buildBannerEmbedHtml(format, affiliateUrl, bannerLang),
    [format, affiliateUrl, bannerLang],
  );

  const label = isAr ? format.label_ar : format.label_en;
  const platform = isAr ? format.platformHint_ar : format.platformHint_en;
  const bannerUrl = getBannerUrl(format, bannerLang);

  return (
    <article className="marble-card flex min-w-0 flex-col p-5">
      <header>
        <h3 className="text-base font-semibold tracking-tight">{label}</h3>
        <p className="mt-1 text-xs font-normal text-[var(--muted-foreground)]">{platform}</p>
      </header>

      {/* Banner preview — renders the banner in its final true form.
          No external card / frame / checkered backdrop: just the banner
          itself, responsively scaled to fit its container width on every
          screen (mobile + desktop). The container clips any sub-pixel
          rounding overflow but never scrolls horizontally (no overflow-x).
          min-w-0 + max-w-full chain breaks the flexbox "intrinsic min-size"
          trap that otherwise forces wide banners (e.g. 728×90) to overflow
          narrow viewports. rounded-2xl gives the banner soft rounded
          corners. The SVG's intrinsic viewBox preserves the original
          aspect ratio automatically — no clipping or distortion. */}
      <div className="mt-4 w-full min-w-0 max-w-full overflow-hidden rounded-2xl">
        <a
          href={affiliateUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="block w-full min-w-0 max-w-full overflow-hidden rounded-2xl"
          aria-label={isAr ? `معاينة بانر ${label}` : `Preview ${label}`}
        >
          {/*
            Note: <img> is intentionally used here (not next/image) because
            the banner is a static SVG asset that doesn't need optimization
            and is embedded as-is by external websites via the HTML embed
            code. No width/height HTML attributes — inline style forces the
            image to fully fill its container while preserving the SVG's
            intrinsic aspect ratio. The width:100% + max-width:100% +
            height:auto + min-width:0 chain guarantees:
              - On mobile: banner shrinks to viewport width (no horizontal
                scroll, no clipping, no distortion)
              - On desktop: banner renders at its natural dimensions up to
                the column width, preserving original aspect ratio
          */}
          {/* eslint-disable-next-line @next/next/no-img-element -- intentional: static SVG banner asset (rationale in the note above); next/image adds no value here */}
          <img
            src={bannerUrl}
            alt={bannerLang === "ar"
              ? "Alkemos — منصة اللياقة والتغذية الذكية. ابدأ مجانًا."
              : "Alkemos — Your AI fitness & nutrition coach. Start free."}
            loading="lazy"
            style={{
              display: "block",
              width: "100%",
              maxWidth: "100%",
              minWidth: 0,
              height: "auto",
              borderRadius: "1rem",
            }}
          />
        </a>
      </div>

      {/* HTML embed code block — keyboard-accessible, wraps long URLs instead
          of forcing horizontal scroll on the parent card. whitespace-pre-wrap
          + break-words let very long lines (e.g. affiliate URLs) wrap inside
          the <pre> instead of becoming intrinsic min-content of the <article>.
          overflow-auto still allows vertical scroll for long snippets. */}
      <div className="mt-4">
        <p className="text-xs font-semibold uppercase tracking-wide text-[var(--muted-foreground)]">
          {isAr ? "كود HTML للدمج" : "HTML Embed Code"}
        </p>
        <pre
          dir="ltr"
          className="mt-2 max-h-40 overflow-auto whitespace-pre-wrap break-words rounded-xl bg-black p-4 text-xs font-mono text-[#DDE0E3]"
          tabIndex={0}
          aria-label={isAr ? "كود HTML" : "HTML code"}
        >
          <code>{html}</code>
        </pre>
      </div>

      {/* Copy HTML button */}
      <footer className="mt-4 flex items-center justify-end gap-3">
        <CopyButton
          value={html}
          label={isAr ? "نسخ HTML" : "Copy HTML"}
          successLabel={ui.common.copied}
          errorLabel={ui.common.copyError}
          variant="secondary"
          analyticsEvent="affiliate_banner_html_copied"
          analyticsPayload={{
            banner: format.id,
            width: format.width,
            height: format.height,
          }}
          ariaLabel={isAr ? `نسخ كود HTML لـ ${label}` : `Copy HTML code for ${label}`}
        />
      </footer>
    </article>
  );
}

// ─────────────────────────────────────────────────────────────────────────
// UI strings (EN + AR)
// ─────────────────────────────────────────────────────────────────────────

type UiStrings = {
  link: {
    title: string;
    subtitle: string;
    inputLabel: string;
    copy: string;
    copyAria: string;
    copied: string;
    error: string;
    note: string;
  };
  content: {
    title: string;
    subtitle: string;
  };
  banners: {
    title: string;
    subtitle: string;
    langSelector: {
      title: string;
      en: string;
      ar: string;
      hint: string;
    };
  };
  common: {
    copied: string;
    copyError: string;
  };
};

function getUi(isAr: boolean): UiStrings {
  if (isAr) {
    return {
      link: {
        title: "رابط الأفلييت بتاعك",
        subtitle:
          "استخدم الرابط ده في كل مكان بتعمل فيه توصية لـ Alkemos. كل عملية شراء مؤهلة تتم عن طريقه بتتسجل في حسابك.",
        inputLabel: "رابط الأفلييت",
        copy: "نسخ الرابط",
        copyAria: "نسخ رابط الأفلييت",
        copied: "تم النسخ ✓",
        error: "تعذر النسخ",
        note:
          "الرابط ده مرتبط بحسابك فقط. متشاركوش مع حد تاني. أي تعديل بيفقد التتبع.",
      },
      content: {
        title: "محتوى جاهز للنشر",
        subtitle:
          "نسخ جاهزة ومناسبة لكل منصة. كل نسخة فيها رابطك الفعلي. متعدلش على النصوص بشكل يخالف الإفصاح عن الأفلييت.",
      },
      banners: {
        title: "بانرات للموقع",
        subtitle:
          "بانرات جاهزة للتركيب على موقعك أو مدونتك. كل بانر فيه كود HTML جاهز للنسخ مباشرة.",
        langSelector: {
          title: "لغة البانر",
          en: "إنجليزي",
          ar: "عربي",
          hint: "اختر اللغة اللي هتشوفها لزوار موقعك في البانر.",
        },
      },
      common: {
        copied: "تم النسخ ✓",
        copyError: "تعذر النسخ",
      },
    };
  }
  return {
    link: {
      title: "YOUR AFFILIATE LINK",
      subtitle:
        "Use this link anywhere you recommend Alkemos. Every eligible purchase made through it is recorded in your account.",
      inputLabel: "Affiliate link",
      copy: "COPY LINK",
      copyAria: "Copy your affiliate link",
      copied: "COPIED ✓",
      error: "Unable to copy",
      note:
        "This link is tied to your account only. Do not share it with anyone else. Any modification breaks tracking.",
    },
    content: {
      title: "READY-TO-PUBLISH CONTENT",
      subtitle:
        "Ready-made copy tailored for each platform. Each piece includes your real affiliate link. Do not edit the affiliate disclosure out of the copy.",
    },
    banners: {
      title: "WEBSITE BANNERS",
      subtitle:
        "Ready-to-embed banners for your site or blog. Each banner comes with copy-ready HTML.",
      langSelector: {
        title: "Banner language",
        en: "English",
        ar: "Arabic",
        hint: "Choose which language your site visitors will see inside the banner.",
    },
    },
    common: {
      copied: "COPIED ✓",
      copyError: "Unable to copy",
    },
  };
}
